# _config.yml

# Project information
title: "aa Notebooks"
author: "ct"
# logo: "path/to/logo.png"  # Optional

# Site URL (for GitHub Pages)
repository:
  url: "https://github.com/tomctang/pe"
  path_to_docs: ""
  branch: "gh-pages"  # Specify the deployment branch

# HTML and theme configuration
html:
  favicon: "path/to/favicon.ico"
  theme:
    name: "sphinx_book_theme"  # Common Jupyter Book theme
    options:
      logo_only: true
      search_bar_position: "navbar"
      extra_navbar: '<p>My Custom Footer</p>'

# Execution options
execute:
  execute_notebooks: "off"  # "auto" to automatically execute notebooks

# Any additional plugins or extensions
sphinx:
  extra_extensions:
    - myst_parser  # Parses markdown
    - sphinx.ext.mathjax  # Renders LaTeX math
