name: Build and Deploy Notebooks

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Check out the repository
      uses: actions/checkout@v4
      
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.9'
      
    - name: Install nbconvert
      run: |
        pip install nbconvert
        
    - name: Convert Notebooks to HTML
      run: |
        mkdir -p output
        for notebook in *.ipynb; do
          jupyter nbconvert --to html "$notebook" --output-dir=output
        done
        
    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v4
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./output
